# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM opensuse/leap:15.2

# Hotfix for en_US.UTF-8 locale
RUN set -ex \
    && zypper -n --gpg-auto-import-keys refresh \
    && zypper -n install -y glibc-i18ndata glibc-locale \
    && zypper clean --all

ENV LANG   "en_US.UTF-8"
ENV LC_ALL "en_US.UTF-8"
ENV SHELL  "/bin/bash"
ENV TZ     "UTC"

# Hotfix for systemd
RUN set -ex \
    && zypper -n --gpg-auto-import-keys refresh \
    && zypper -n install -y systemd systemd-sysvinit \
    && rm -f /etc/systemd/system/*.wants/* \
    && rm -f /usr/lib/systemd/system/basic.target.wants/* \
    && rm -f /usr/lib/systemd/system/local-fs.target.wants/* \
    && rm -f /usr/lib/systemd/system/multi-user.target.wants/* \
    && rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl* \
    && rm -f /usr/lib/systemd/system/sockets.target.wants/*udev* \
    && rm -f /usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service \
    && zypper clean --all
